#ifndef LAYOUT_H
#define LAYOUT_H

#define CELL_HEIGHT 3
#define CELL_WIDTH 9

#define GRID_HEIGHT ((CELL_HEIGHT * 9) + 10)
#define GRID_WIDTH ((CELL_WIDTH * 9) + 10)
#define GRID_START_Y 0
#define GRID_START_X ((COLS - GRID_WIDTH) / 2)

#define INFO_HEIGHT (LINES - GRID_HEIGHT)
#define INFO_WIDTH (COLS - SCROLLBAR_WIDTH - 1)
#define INFO_START_Y GRID_HEIGHT
#define INFO_START_X 0

#define SCROLLBAR_HEIGHT (LINES - GRID_HEIGHT)
#define SCROLLBAR_WIDTH 1
#define SCROLLBAR_START_Y GRID_HEIGHT
#define SCROLLBAR_START_X (COLS - SCROLLBAR_WIDTH)

#endif
